nodes:
  Source: { initial: 1000.0, capacity: 1000.0, process_factor: 1.0 }
  A: { initial: 0.0, capacity: 200.0, process_factor: 0.8 }
  B: { initial: 0.0, capacity: 300.0, process_factor: 0.9 }
  C: { initial: 0.0, capacity: 250.0, process_factor: 0.7 }
  D: { initial: 0.0, capacity: 400.0, process_factor: 0.85 }
  E: { initial: 0.0, capacity: 350.0, process_factor: 0.75 }
  F: { initial: 0.0, capacity: 280.0, process_factor: 0.95 }
  Sink: { initial: 0.0, capacity: 2000.0, process_factor: 1.0 }

edges:
  # メインフロー
  - { source: Source, target: A, transfer_rate: 0.02, loss: 0.05 }
  - { source: A, target: B, transfer_rate: 0.04, loss: 0.1 }
  - { source: B, target: C, transfer_rate: 0.03, loss: 0.05 }
  - { source: C, target: D, transfer_rate: 0.05, loss: 0.08 }
  - { source: D, target: E, transfer_rate: 0.04, loss: 0.12 }
  - { source: E, target: F, transfer_rate: 0.06, loss: 0.07 }
  - { source: F, target: Sink, transfer_rate: 0.07, loss: 0.03 }

  # 分岐フロー
  - { source: A, target: D, transfer_rate: 0.03, loss: 0.15 }
  - { source: B, target: E, transfer_rate: 0.02, loss: 0.1 }
  - { source: C, target: F, transfer_rate: 0.025, loss: 0.08 }

  # フィードバックループ
  - { source: D, target: B, transfer_rate: 0.015, loss: 0.2 }
  - { source: E, target: C, transfer_rate: 0.018, loss: 0.15 }
  - { source: F, target: D, transfer_rate: 0.012, loss: 0.18 }
